version: "3"
services:
  api1:
    image: api-dart
    container_name: api-dart1
    depends_on:
      - db
    networks:
      - net
  api2:
    image: api-dart
    container_name: api-dart2
    depends_on:
      - db
    networks:
      - net
  db:
    image: mongo:4.0
    container_name: video-movies-db
    networks:
      - net
    volumes:
      - ./var/db:/data/db
    ports:
      - 27017:27017
  nginx:
    image: nginx:alpine
    container_name: video-movies-nginx
    depends_on:
      - api1
      - api2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - net
    ports:
      - 3333:80
networks:
  net:
    driver: 'bridge'