GET http://localhost:3333/videomovies?skip=10&limit=10

###
GET http://localhost:7777/

###
GET http://localhost:4444/api-java/videomovies

###

GET http://localhost:8008/videomovies/56918f5e24de1e0ce2dfcccd

###
GET http://localhost:8008/videomovies/count

###
GET http://localhost:8008/videomovies/tt0076759/details