name: models
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Aleksey Danilevskiy <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  data_model:
    git:
      url: https://github.com/alexd1971/data_model.git
      ref: master

dev_dependencies:
  test: ^1.0.0
